package es.rpjd.app.hibernate.sql;

public class SQLQueries {
	
	private SQLQueries() {}

	public static final String SELECT_ORDERS_QUANTITY_TODAY = "SELECT COUNT(*) FROM CUSTOMER_ORDER WHERE CREATED_AT BETWEEN CURDATE() AND CURDATE() + INTERVAL 1 DAY - INTERVAL 1 SECOND";
	public static final String SELECT_ORDERS_BY_CODE = "SELECT * FROM CUSTOMER_ORDER WHERE ORDER_CODE = :code";
	public static final String SELECT_UNPROCESSED_ORDERS = "SELECT * FROM CUSTOMER_ORDER WHERE PROCESSED = 0";
	public static final String SELECT_PROCESSED_ORDERS = "SELECT * FROM CUSTOMER_ORDER WHERE PROCESSED = 1";
}
